# Generated by Django 2.2.3 on 2019-08-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Number',
            field=models.IntegerField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Number',
            field=models.IntegerField(auto_created=True, blank=True),
        ),
    ]
