# Generated by Django 2.2.3 on 2019-08-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190802_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.IntegerField(default=0)),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Answer')),
                ('Parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Parameter')),
            ],
        ),
    ]
