# Generated by Django 2.2.3 on 2019-08-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190809_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Layout',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
