# Generated by Django 2.2.3 on 2019-08-11 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_quiz_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='State',
            field=models.CharField(blank=True, default='1', max_length=40),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Answer')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
