# Generated by Django 2.2.3 on 2019-08-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190811_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Number',
            field=models.IntegerField(auto_created=True, blank=True, default=0, null=True),
        ),
    ]
