# Generated by Django 2.2.3 on 2019-08-11 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_quiz_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Student'),
        ),
    ]
